---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    purpose: media-applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: monitoring-tools
---
apiVersion: v1
kind: Namespace
metadata:
  name: openbao
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
