apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-ingress-host
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-eso
    kind: ClusterSecretStore
  target:
    name: argocd-ingress-host
  data:
  - secretKey: hostname
    remoteRef:
      key: secret/hosts/argocd-host-secret
      property: value
